# Generated by Django 3.2.12 on 2023-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230606_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
